apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-db
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.db.user | quote }}
  password: {{ .Values.db.password | quote }}
